import type { Metadata } from "next";

import "./globals.css";
import ThemeRegistry from "./ThemeRegistry";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./contexts/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body className={`antialiased`}>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </body>
      </ThemeRegistry>
    </html>
  );
}
